import { Geist, Geist_Mono, Comic_Neue } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Customer Management System",
  description: "Generated by Cursor and Human Input",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
